\documentclass[letterpaper]{article}
%\VignetteIndexEntry{Generalized Ridge and Least Angle Regression: Calculations and Visualizations}
%\VignettePackage{RXshrink}

\usepackage{pdfpages}

\begin{document}

\newread\PDFtoInclude
\openin\PDFtoInclude=shrink0.pdf
\ifeof\PDFtoInclude
\typeout{No file shrink0.pdf}
\else
\includepdf[fitpaper=true,pages=-]{shrink0.pdf}
\fi

\end{document}
